# Generated by Django 4.0 on 2021-12-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenido', '0003_alter_departamento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=None),
        ),
    ]
